version: '3'
networks:
  airflow:
    driver: bridge
services:
  airflow-database:
    container_name: airflow-database
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
    networks:
      - airflow
  airflow-init:
    container_name: airflow-init
    depends_on:
      - airflow-database
    image: apache/airflow:2.6.1-python3.10
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:1234@airflow-database:5432/airflow
    entrypoint: /bin/bash
    command: |-
      -c "
      airflow db init && \
      airflow users create --username admin --password 1234 --firstname Jerry --lastname Park --role Admin --email jerry@innopam.com
      "
    restart: on-failure
    networks:
      - airflow
  airflow-scheduler:
    container_name: airflow-scheduler
    depends_on:
      - airflow-init
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:1234@airflow-database:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./share_folder:/opt/airflow/share_folder
      - ./tiles:/opt/airflow/tiles
    command: airflow scheduler
    restart: always
    networks:
      - airflow
  airflow-webserver:
    container_name: airflow-webserver
    depends_on:
      - airflow-init
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:1234@airflow-database:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./share_folder:/opt/airflow/share_folder
      - ./tiles:/opt/airflow/tiles
    command: airflow webserver
    ports:
      - 8888:8080
    restart: always
    networks:
      - airflow
  gdal:
    image: osgeo/gdal:ubuntu-small-lates
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./gdal:/gdal_data
     # - ./app:/app
    #command: [ "pip", "install", "--no-cache-dir", "-r", "/app/requirements.txt" ]
    networks:
      - airflow



